hoos_study/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hoos_study_app.urls")),
    path('accounts/', include("allauth.urls")),
]

# Settings for django to serve files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoos_study_app/urls.py
from django.urls import path

from . import views

app_name = "hoos_study_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("classes/", views.ClassesView.as_view(), name="class-list"),

    path("all-study-session-preview/", views.anon_list_study_sessions, name="all-study-sessions-preview"),

    path("pma-manage-study-sessions/", views.pma_manage_study_sessions, name="pma-manage-study-sessions"),
    path("pma-manage-study-sessions/<int:session_id>/delete", views.pma_delete_study_session, name='pma_delete_study_session'),

    path("documents/upload/", views.upload_file, name="upload"),
    path("documents/", views.DocumentsListView.as_view(), name="documents"),
    path("documents/<int:pk>", views.delete_document, name="delete_document"),
    path('course/<int:course_id>/<int:session_id>/upload/', views.upload_file_study_session, name='upload_file_study_session'),
    path("course/<int:course_id>/<int:session_id>", views.study_session_dashboard, name='study_session_dashboard'),
    path("course/<int:pk>/<int:course_id>/<int:session_id>", views.delete_document, name='delete_document'),
    path("study-session/<int:session_id>/delete/", views.delete_study_session, name='delete_study_session'),
    path("study-session/<int:session_id>/join/", views.join_study_session, name='join_study_session'),
    path("study-session/<int:session_id>/leave/", views.leave_study_session, name='leave_study_session'),

    path('course/<int:course_id>/create-study-session/', views.create_study_session, name='create-study-session'),
    path('join-study-session/<int:session_id>/', views.join_study_session, name='join_study_session'),
    path('manage-join-request/<int:request_id>/<str:action>/', views.manage_join_request, name='manage_join_request'),


    # path("course/<int:course_id>/message_board", views.message_board_view, name="course_group"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('change-background/', views.change_background, name='change_background'),

    path("study-session/", views.all_study_sessions, name='all-study-sessions'),
    path('add-location/', views.add_location, name='add-location'),
    # path('create-study-session/', views.create_study_session, name='create-study-session'),
    path("availability/<int:session_id>", views.give_availability, name='give-availability'),
    path("my-study-sessions", views.my_study_sessions, name='my-study-sessions'),
    path('message/delete/<int:message_id>/', views.delete_message, name='delete_message'),

    path('course/<int:pk>/', views.CourseGroupView.as_view(), name='course_group'),
    path('course/<int:course_id>/join/', views.join_course_group, name='join_course_group'),
    path('course/<int:course_id>/leave/', views.leave_course_group, name='leave_course_group')
]

hoos_study_app/views.py
from django.db import transaction
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.db.models import Q
from collections import defaultdict

# imports for google authentication
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# imports for creating user accounts
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView

# imports for upload_file
from django.contrib.auth.models import AnonymousUser
from django.http import HttpResponseRedirect
from django.forms import HiddenInput
# # from django.shortcuts import render
from .forms import UploadFileForm, LocationForm, StudySessionForm, AvailabilityForm, UserProfileForm, ProfilePictureForm, SelectDefaultPictureForm
# , CreateUserForm
# from .models import User
from . import forms, models
from .models import JoinRequest, StudySession, StudySessionAvailability, Course, Message, MessageBoard, Document, UserCoursePreference
from datetime import datetime, timedelta
from collections import Counter
from django.views.decorators.cache import cache_control
import time, os, random, boto3
from django.utils.timezone import localdate
from django.contrib import messages
# imports for editing/deleting messages
from django.http import JsonResponse, HttpResponseRedirect , HttpResponseForbidden
from django.core.exceptions import PermissionDenied

# Class/Study group page
@login_required
def leave_course_group(request, course_id):
    # Fetch the course by ID
    course = get_object_or_404(Course, id=course_id)

    # Remove the current user from the course's student list if they are a member
    course.students.remove(request.user)
    # Delete the user's preferences for this course
    UserCoursePreference.objects.filter(user=request.user, course=course).delete()
    
    messages.success(request, f"You have successfully left {course.mnemonic} {course.number}.")

    # Redirect to the course group page
    return redirect('hoos_study_app:dashboard')

@login_required
def join_course_group(request, course_id):
    # Fetch the course by ID
    course = get_object_or_404(Course, id=course_id)

    # Add the current user to the course's student list
    course.students.add(request.user)
    UserCoursePreference.objects.get_or_create(user=request.user, course=course)
    course.save()
    
    messages.success(request, f"You have successfully joined {course.mnemonic} {course.number}.")

    return redirect('hoos_study_app:course_group', pk=course.id)

class CourseGroupView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'hoos_study_app/course_group.html'
    context_object_name = 'course'

    def get_object(self):
        # Fetch the course by its ID or slug from the URL
        course_id = self.kwargs.get("pk")
        return get_object_or_404(Course, pk=course_id)
    
    # Handle POST for message board    
    def post(self, request, *args, **kwargs):
        course = self.get_object()
        board = get_object_or_404(MessageBoard, course=course)
        content = request.POST.get('content', '')
        is_anonymous = request.POST.get("is_anonymous") == "on"
        # messages = board.messages.select_related('user').order_by('timestamp')


        if content:
            Message.objects.create(
                message_board=board,
                user=request.user,
                content=content,
                is_anonymous=is_anonymous,
            )
        
        # Redirect back to the same page after handling POST
        return redirect('hoos_study_app:course_group', pk=course.id)

    def get_context_data(self, **kwargs):
        # Get the base context from DetailView
        context = super().get_context_data(**kwargs)
        course = self.get_object()

        today = localdate()

        # Add additional data to the context
        context['documents'] = Document.objects.filter(course=course)
        context['message_board'] = course.message_board
        context['students'] = course.students.all()
        context['all_study_sessions'] = StudySession.objects.filter(course_name=course).order_by('date')
        context['upcoming_study_sessions'] = StudySession.objects.filter(course_name=course).filter(date__gte=today).order_by('date')
        context['past_study_sessions'] = StudySession.objects.filter(course_name=course).filter(date__lt=today).order_by('-date')
        context['background_image'] = UserCoursePreference.objects.get(user=self.request.user, course=course).background_image

        # Add message board data
        board = course.message_board
        messages = board.messages.select_related('user').order_by('-timestamp')
        context['board_messages'] = messages
        context['current_user'] = self.request.user

        context['submitted'] = 'submitted' in self.request.GET

        return context

class ClassesView(ListView):
    model = Course
    template_name = "hoos_study_app/classes.html"
    context_object_name = "class_list"

    def get_queryset(self):
        return Course.objects.order_by('mnemonic', 'number')

def home(request):
    if request.user.is_authenticated:
        # Redirect to the dashboard for logged-in users
        return redirect('hoos_study_app:dashboard')
    else:
        return render(request, template_name="hoos_study_app/index.html")

# Helper function
def get_profile_pictures():
    if settings.USE_S3:
        # Connect to S3
        s3 = boto3.resource('s3')
        # Access the bucket and get objects
        bucket = s3.Bucket(settings.AWS_STORAGE_BUCKET_NAME)
        objects = bucket.objects.filter(Prefix=f'{settings.MEDIA_LOCATION}/profile_pictures/default_profile_pictures/')

        images = [os.path.basename(obj.key) for obj in objects if not obj.key.endswith('/')]
        return images
    else:
        # Use local storage
        img_path = os.path.join(settings.MEDIA_ROOT, 'profile_pictures/default_profile_pictures/')
        images = os.listdir(img_path)
        return images

@login_required
def profile(request):
    user = request.user

    images = get_profile_pictures()
    
    # Initialize forms
    account_details_form = UserProfileForm(instance=user)
    upload_picture_form = ProfilePictureForm(instance=user)
    default_picture_form = SelectDefaultPictureForm()

    if request.method == 'POST':
        if 'account_details_update' in request.POST:
            account_details_form = UserProfileForm(request.POST, instance=user)
            if account_details_form.is_valid():
                account_details_form.save()
                messages.success(request, "Your profile has been updated successfully.")
                return redirect('hoos_study_app:profile')
        elif 'upload_picture' in request.POST:
            upload_picture_form = ProfilePictureForm(request.POST, request.FILES, instance=user)

            if upload_picture_form.is_valid():
                upload_picture_form.save()
                messages.success(request, "Your profile picture has been updated successfully.")
                return redirect('hoos_study_app:profile')
            
        elif 'select_default' in request.POST:
            default_picture_form = SelectDefaultPictureForm(request.POST)

            if default_picture_form.is_valid():
                selected_picture = default_picture_form.cleaned_data['selected_default_picture']
                user.profile_picture = f'profile_pictures/default_profile_pictures/{selected_picture}'
                user.save()
                messages.success(request, "Your profile picture has been updated successfully.")
                return redirect('hoos_study_app:profile')
    
    # Render the template
    return render(request, 'hoos_study_app/profile.html', {
        'form': account_details_form,
        'upload_picture_form': upload_picture_form,
        'default_picture_form': default_picture_form,
        'default_pictures': images,
        'creation_date': user.date_joined,
    })

def logout_view(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return redirect("hoos_study_app:home")

# Upload and display documents (video series): https://www.youtube.com/watch?v=Zx09vcYq1oc
class DocumentsListView(LoginRequiredMixin, ListView):
    model = models.Document
    template_name = "hoos_study_app/documents.html"
    context_object_name = "documents"

    def get_queryset(self):
        # # Only return documents that belong to the logged-in user
        # return models.Document.objects.filter(author=self.request.user)

        # Get the search query from the GET request
        query = self.request.GET.get('q')

        # Start with the base queryset (documents for the logged-in user)
        queryset = models.Document.objects.filter(author=self.request.user)

        # If there is a search query, filter the queryset across multiple fields
        if query:
            queryset = queryset.filter(
                Q(filename__icontains=query) |
                Q(description__icontains=query) |
                Q(course__mnemonic__icontains=query) |  # Searches Course mnemonic
                Q(course__number__icontains=query) |    # Searches Course number
                Q(course__title__icontains=query) |     # Searches Course title
                Q(keywords__name__icontains=query)      # Searches Keyword name
            ).distinct()
        return queryset



# @login_required(login_url='hoos_study_app:documents')
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            document = form.save(commit=False)
            document.author = request.user
            document.save()

hoos_study_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}HoosStudy{% endblock %}</title>

    <!-- Custom styles (takes precedence first)-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'hoos_study_app/css/styles.css' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body class="d-flex flex-column min-vh-100">
  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossorigin="anonymous"></script>

  <header class="navbar navbar-expand-lg py-3" style="background-color: #232D4B;">
    <nav class="container-xxl px-5">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon navbar-dark"></span>
      </button>

      <div class="collapse navbar-collapse text-light" id="navbarToggler">
        <a class="navbar-brand d-flex align-items-center me-5 fw-bold text-light" href="{% url 'hoos_study_app:home' %}" style="text-decoration: none;">
            <img src="{% static 'hoos_study_app/img/rotundaIcon.png' %}"
                alt="Rotunda Icon"
                style="width: 35px; height: 35px; margin-right: 10px;">
            <span style="font-size: 1.5rem; font-weight: bold;">Hoos<span style="color: #FF8200;">Study</span></span>
        </a>
        <a class="nav-link me-4" href="{% url 'hoos_study_app:class-list' %}">
          All Classes
        </a>
        {% if not user.is_authenticated %}
          <a class="nav-link me-4" href="{% url 'hoos_study_app:all-study-sessions-preview' %}">
            Study Sessions
          </a>
        {% endif %}
        {% if user.is_pma_admin %}
        <a class="nav-link me-4" href="{% url 'hoos_study_app:pma-manage-study-sessions' %}">
          Manage Study Sessions
        </a>
        {% endif %}
      </div>

      <div class="ms-auto">
        {% if user.is_authenticated %}
        <div class="d-flex align-items-center text-light">
          <p class="me-3 mb-0">Hi, {{ user.first_name }}!</p>
          <div id="profile-picture-dropdown" class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img id="profile-picture" 
                 class="rounded-circle" 
                 src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% endif %}" 
                 style="width: 45px; height: 45px; object-fit: cover;">
            </a>
            <ul class="dropdown-menu dropdown-menu-end w-auto">
              <li><a class="dropdown-item" href="{% url 'hoos_study_app:profile' %}"><i class="bi bi-person-fill me-3"></i>My Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'hoos_study_app:documents' %}"><i class="bi bi-files me-3"></i>My Documents</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item text-danger" href="" data-bs-toggle="modal" data-bs-target="#logoutModal">
                  <i class="bi bi-box-arrow-left me-3"></i>Log Out
                </a>
              </li>
            </ul>
          </div>
        </div>
        {% else %}
          <a href="{% url 'account_login' %}" class="btn btn-light">
            <i class="bi bi-box-arrow-in-right me-1"></i>
            Log In
          </a>
        {% endif %}
      </div>
      
    </nav>
  </header>

  {% block main %} <!-- This block only used by homepage (index.html) -->
  <div id="content" class="container-xxl px-5 flex-grow-1 my-4 text-info-emphasis">
    {% if messages %}
      {% for message in messages %}
        <div role="alert" class="alert alert-{{ message.tags }} alert-dismissible fade show">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}{% endblock %}
  </div>
  {% endblock main %}

  <div class="py-5" style="background-color: #C8CBD2;">
    <footer class="container-xxl text-center text-info-emphasis">
      <p>© 2024 CS3240 Fall2024 B-02</p>
    </footer>
  </div>

  <!-- Modal for Logout -->
  <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="logoutModalLabel">Confirm Logout</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to log out?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <a href="{% url 'hoos_study_app:logout' %}" class="btn btn-danger">Confirm Logout</a>
        </div>
      </div>
    </div>
  </div>

  {% block scripts %}{% endblock %}
</body>

hoos_study_app/templates/base2.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HoosStudy Class List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid p-3 mb-2 bg-primary-subtle text-primary-emphasis">
    <a class="navbar-brand" href="{% url 'hoos_study_app:class-list' %}">
        Home
    </a>
      <a class="navbar-brand" href="{% url 'hoos_study_app:all-study-sessions' %}">
        Study Sessions
      </a>



      <a class="navbar-brand" href="{% url 'hoos_study_app:create-study-session' %}">
        Create Study Session
      </a>
  </div>
</nav>



    <div id="content" class="p-3 mb-2 bg-info-subtle text-info-emphasis">
        {% block content %}{% endblock %}
    </div>

<div class="container">
  <footer class="py-3 my-4">
    <p class="text-center text-body-secondary">© 2024 CS3240 Fall2024 B-02</p>
  </footer>
</div>
</body>

hoos_study_app/templates/login_signup_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- Custom styles (takes precedence first)-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'hoos_study_app/css/styles.css' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <style>
        .bg-image {
          background-image: url("{% static 'hoos_study_app/img/rotunda.jpg' %}");
          background-size: cover;
          background-position: center;
        }
    </style>

    <div class="container-fluid ps-md-0">
        <div class="row g-0">
            <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
            <div class="col-md-8 col-lg-6">
                <div class="vh-100 d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9 col-lg-8 mx-auto">
                                {% block content %}{% endblock %}
                                <div class="mt-4">
                                    <a href="{% url 'hoos_study_app:home' %}" class="link-secondary link-offset-1 fs-6">Go back to homepage</a>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>